### PR TITLE
Added the ability to add new buttons beside the toggle button

### PR DESCRIPTION
**Pull request by hyyan**
Added the ability to add new buttons beside the toggle button and updated the demo

### CODE REVIEW

**Comment by ronnyroeller** [comment]
Thanks for your contribution, @hyyan !

Could you please look to the following two points:
- Add documentation that the element allow <content> to be included (https://github.com/Collaborne/paper-collapse-item/blob/master/paper-collapse-item.html#L11https://github.com/Collaborne/paper-collapse-item/blob/master/paper-collapse-item.html#L11)
- I'd prefer to not auto-style the embedded content but let the caller do this (https://github.com/Collaborne/paper-collapse-item/pull/13/files#diff-18efb91d4541bb9a2135b57c1d49d123R61). Making embedded icons grey is a bit "magical".

**Comment by ankon** [comment]
The build failure should be fixed with the latest master, please also rebase to this version.

**Comment by hyyan** [comment]
@ankon  Sure I will do a rebase 

@ronnyroeller I have added the style to fit the toggle button , is not this expected ?

**Comment by hyyan** [comment]
@ankon the build is passing now , I have made a rebase

**Comment by ronnyroeller** [comment]
> I have added the style to fit the toggle button , is not this expected ?

I see the following scenario where the user's expectation might be broken: Users can add any kind of element to `<content>`. We would normally just output these elements. But if this happens to be an `paper-icon-button` it gets magically formatted. For example: If the user would insert instead an `iron-icon` it wouldn't do that, i.e. this behaves somehow differently.

I do see your point that the user looses control as the element might change the color of the icon, thereby making the icons inconsistent. Hence, an idea: How about we give the user control over the color of all standard icons (the color being default to `--disabled-text-color`). Then users could define their application how to color the all standard and custom icons (e.g. by fixing it to `--disabled-text-color` or to another color).
What think?

**Comment by hyyan** [comment]
@ronnyroeller I think you are correct , I have to admit I have missed that,  adding a default color for `paper-icon-button` is not a good idea . Giving the user the ability to set the default color for icons is much better.

I will remove the default coloring from this PR , and send a new one Which adds the ability to set the default color for icons 

Is this sounds Ok like this  ?

**Comment by ronnyroeller** [comment]
Perfect!

**Comment by ronnyroeller** [comment]
(Could you please remove all unrelated commits from the PR?)

**Comment by hyyan** [comment]
@ronnyroeller yes sure I will fix this PR later this week , I was just too busy with other stuffs

**Pull request merged**
